# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Perl::Maven"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "system"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

mymaven:
  default:
    lang: 'en'
    title: 'Perl 5 Maven'
    from: 'Perl 5 Maven <gabor@perl5maven.com>'
    listid: 'Perl 5 Maven newsletter <newsletter.perl5maven.com>'
    prefix: '[Perl Maven]'
    rss:
      title: 'Perl 5 Maven'
      url: 'http://perl5maven.com'
    admin:
      email: 'Gabor Szabo <gabor@szabgab.com>'
    paypal:
      email: 'gabor@szabgab.com'
    articles: '/home/gabor/work/articles'
  br.perl5maven.local:
    lang: 'br'
    articles: '/home/gabor/work/br.perl5maven.com'
  br.perl5maven.com:
    lang: 'br'
    articles: '/home/gabor/work/br.perl5maven.com'


template: "template_toolkit"
engines:
  template_toolkit:
    INCLUDE_PATH: '/home/gabor/work/Perl-Maven/views'
    encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

session: "YAML"
