# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Perl::Maven"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "system"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

mymaven:
  default:
    lang: 'en'
    title: 'Perl 5 Maven'
    from: 'Perl 5 Maven <gabor@perl5maven.com>'
    listid: 'Perl 5 Maven newsletter <newsletter.perl5maven.com>'
    prefix: '[Perl Maven]'
    conf:
      clicky: 66509177
      google_analytics: UA-12199211-9
    rss:
      title: 'Perl 5 Maven'
      url: 'http://perl5maven.com'
    admin:
      email: 'Gabor Szabo <gabor@szabgab.com>'
    paypal:
      email: 'gabor@szabgab.com'
    download: '/home/gabor/work/articles/download'
  perlmaven.com:
    conf:
      clicky: 100527028
      google_analytics: UA-12199211-13
    articles: '/home/gabor/work/perlmaven.com/articles'
    meta: '/home/gabor/work/articles/perlmaven.com/meta'
    rss:
      title: 'Perl Maven Show'
      url: 'http://perlmaven.com'
  perlmaven.win32:
    conf:
      clicky: 100527028
      google_analytics: UA-12199211-13
    articles: 'c:/work/perlmaven.com/articles'
    meta: 'c:/work/articles/perlmaven.com/meta'
    rss:
      title: 'Perl Maven Show'
      url: 'http://perlmaven.com'
  perl5maven.win32:
    root: 'c:/work/perl5maven.com/sites/en'
    meta: 'c:/work/articles/perl5maven.com/meta'
    mail: 'c:/work/articles/mail'
    perldoc: 'c:/work/articles/perldoc'
  perl5maven.local:
    root: '/home/gabor/work/perl5maven.com/sites/en'
    meta: '/home/gabor/work/articles/perl5maven.com/meta'
    mail: '/home/gabor/work/articles/mail'
    video: '/home/gabor/work/articles/video'
    perldoc: '/home/gabor/work/articles/perldoc'
  perl5maven.com:
    root: '/home/gabor/work/perl5maven.com/sites/en'
    meta: '/home/gabor/work/articles/perl5maven.com/meta'
    mail: '/home/gabor/work/articles/mail'
    video: '/home/gabor/work/articles/video'
    perldoc: '/home/gabor/work/articles/perldoc'
  br.perl5maven.local:
    lang: 'br'
    root: '/home/gabor/work/perl5maven.com/sites/br'
    meta: '/home/gabor/work/articles/br.perl5maven.com/meta'
  br.perl5maven.com:
    lang: 'br'
    title: 'Perl 5 Maven em Português'
    root: '/home/gabor/work/perl5maven.com/sites/br'
    meta: '/home/gabor/work/articles/br.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven em Português'
      url: 'http://br.perl5maven.com'
  cn.perl5maven.com:
    lang: 'cn'
    title: 'Perl 5 Maven in Chinese'
    root: '/home/gabor/work/perl5maven.com/sites/cn'
    meta: '/home/gabor/work/articles/cn.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Chinese'
      url: 'http://cn.perl5maven.com'
  de.perl5maven.com:
    lang: 'de'
    title: 'Perl 5 Maven in German'
    root: '/home/gabor/work/perl5maven.com/sites/de'
    meta: '/home/gabor/work/articles/de.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in German'
      url: 'http://de.perl5maven.com'
  es.perl5maven.com:
    lang: 'es'
    title: 'Perl 5 Maven en Español'
    root: '/home/gabor/work/perl5maven.com/sites/es'
    meta: '/home/gabor/work/articles/es.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven en Español'
      url: 'http://es.perl5maven.com'
  it.perl5maven.com:
    lang: 'it'
    title: 'Perl 5 Maven in Italian'
    root: '/home/gabor/work/perl5maven.com/sites/it'
    meta: '/home/gabor/work/articles/it.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Italian'
      url: 'http://it.perl5maven.com'
  ko.perl5maven.com:
    lang: 'ko'
    title: 'Perl 5 Maven in Korean'
    root: '/home/gabor/work/ko.perl5maven.com/sites/ko'
    meta: '/home/gabor/work/articles/ko.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Korean'
      url: 'http://ko.perl5maven.com'
  ro.perl5maven.com:
    lang: 'ro'
    title: 'Perl 5 Maven in Romanian'
    root: '/home/gabor/work/perl5maven.com/sites/ro'
    meta: '/home/gabor/work/articles/ro.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Romanian'
      url: 'http://ro.perl5maven.com'
  ru.perl5maven.com:
    lang: 'ru'
    title: 'Perl 5 Maven in Russian'
    root: '/home/gabor/work/perl5maven.com/sites/ru'
    meta: '/home/gabor/work/articles/ru.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Russian'
      url: 'http://ru.perl5maven.com'
  tw.perl5maven.com:
    lang: 'tw'
    title: 'Perl 5 Maven in Chinese (Taiwan)'
    root: '/home/gabor/work/perl5maven.com/sites/tw'
    meta: '/home/gabor/work/articles/tw.perl5maven.com/meta'
    rss:
      title: 'Perl 5 Maven in Chinese (Taiwan)'
      url: 'http://tw.perl5maven.com'


template: "template_toolkit"
engines:
  template_toolkit:
    INCLUDE_PATH: '/home/gabor/work/Perl-Maven/views'
    encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

session: "YAML"
