# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Perl::Maven"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "system"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

mymaven:
  default:
    title: 'Perl 5 Maven'
    root: '/home/gabor/work/perl5maven.com'
    from: 'Perl 5 Maven <gabor@perl5maven.com>'
    listid: 'Perl 5 Maven newsletter <newsletter.perl5maven.com>'
    prefix: '[Perl Maven]'
    conf:
      clicky: 66509177
      google_analytics: UA-12199211-9
    admin:
      email: 'Gabor Szabo <gabor@szabgab.com>'
    paypal:
      email: 'gabor@szabgab.com'
    download: '/home/gabor/work/articles/download'
    meta: '/home/gabor/work/articles'
  perlmaven.com:
    title: 'Perl Maven'
    conf:
      clicky: 100527028
      google_analytics: UA-12199211-13
    root: '/home/gabor/work/perlmaven.com'
    meta: '/home/gabor/work/articles/perlmaven.com/meta'
    media: '/home/gabor/work/media.perlmaven.com'
  perlmaven.local:
    title: 'Perl Maven'
    root: '/home/gabor/work/perlmaven.com'
    media: '/home/gabor/work/media.perlmaven.com'
  perlmaven.win32:
    conf:
      clicky: 100527028
      google_analytics: UA-12199211-13
    articles: 'c:/work/perlmaven.com/articles'
    meta: 'c:/work/articles/perlmaven.com/meta'
  perl5maven.win32:
    mail: 'c:/work/articles/mail'
    perldoc: 'c:/work/articles/perldoc'
  perl5maven.local:
    mail: '/home/gabor/work/articles/mail'
    perldoc: '/home/gabor/work/articles/perldoc'
  perl5maven.com:
    mail: '/home/gabor/work/articles/mail'
    perldoc: '/home/gabor/work/articles/perldoc'


template: "template_toolkit"
engines:
  template_toolkit:
    INCLUDE_PATH: '/home/gabor/work/Perl-Maven/views'
    encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

session: "YAML"
